# Generated by Django 3.2.4 on 2021-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminTG', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='id бота')),
                ('name', models.TextField(verbose_name='Название бота')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
    ]
