# Generated by Django 3.2.4 on 2021-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminTG', '0004_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='botToken',
            field=models.TextField(default='1', verbose_name='Токен бота'),
        ),
    ]
