# Generated by Django 3.2.4 on 2021-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminTG', '0005_bot_bottoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='botToken',
            field=models.TextField(default='', verbose_name='Токен бота'),
        ),
    ]
