# Generated by Django 3.2.4 on 2021-06-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminTG', '0006_alter_bot_bottoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
