# Generated by Django 3.2.4 on 2021-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminTG', '0008_auto_20210624_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sheet',
            field=models.TextField(default='', verbose_name='Ссылка на гугл таблицу'),
        ),
    ]
