# Generated by Django 3.2.4 on 2021-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminTG', '0009_category_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='ID заказа')),
                ('order_name', models.TextField(verbose_name='Содержимое заказа')),
                ('order_cost', models.IntegerField(default=0, verbose_name='Стоимость заказа')),
                ('order_date', models.IntegerField(default=0, verbose_name='Дата заказа')),
            ],
        ),
    ]
